apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb
resources:
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - statefulset.yaml
  - service.yaml
  - configmap.yaml
