apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wireguard
  labels:
    app: wireguard
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      volumes:
        - name: wg0-privatekey
          secret:
            secretName: wg0-privatekey
        - name: wg0-conf
          configMap:
            name: wg0-conf
        - name: scripts
          configMap:
            name: scripts
            defaultMode: 0777
      containers:
        - name: wireguard
          image: ghcr.io/gdrapp/wireguard-container:master
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["wg-quick", "up", "wg0"]
            preStop:
              exec:
                command: ["wg-quick", "down", "wg0"]
          command: ["tail", "-f", "/dev/null"]
          volumeMounts:
            - name: wg0-privatekey
              mountPath: /etc/wireguard/wg0.privatekey
              subPath: privatekey
              readOnly: true
            - name: wg0-conf
              mountPath: /etc/wireguard/wg0.conf
              subPath: wg0.conf
              readOnly: true
            - name: scripts
              mountPath: /usr/local/sbin
              readOnly: true
          ports:
            - containerPort: 51820
              protocol: UDP
          securityContext:
            privileged: true
            capabilities:
              add:
                - NET_ADMIN
