apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
    selector:
        app: influxdb
    type: LoadBalancer
    loadBalancerIP: 192.168.0.39
    ports:
      - name: influxdb
        port: 8086
        targetPort: 8086