apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: esphome
resources:
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: esphome
    newName: ghcr.io/esphome/esphome
    newTag: 2023.4.1
