apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: esphome
  name: esphome-config-nfs
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.8
    path: "/volume1/esphome-config"