apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: esphome
  labels:
    app: esphome
spec:
  replicas: 1
  serviceName: esphome
  selector:
    matchLabels:
      app: esphome
  template:
    metadata:
      labels:
        app: esphome
    spec:
      containers:
        - name: esphome
          image: esphome
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6052
          volumeMounts:
            - mountPath: /config
              name: esphome-config
          resources:
            requests:
              memory: 128Mi
              cpu: 20m
      volumes:
        - name: esphome-config
          persistentVolumeClaim:
            claimName: esphome-config
