apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtlamr
  labels:
    app: rtlamr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtlamr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: rtlamr
    spec:
      containers:
        - name: rtlamr
          image: ghcr.io/gdrapp/rtlamr-mqtt-container:master
          imagePullPolicy: Always
          env:
            - name: MQTT_HOST
              value: mosquitto.mosquitto.svc.cluster.local
            - name: MQTT_PORT
              value: "1883"
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mqtt
                  key: username
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt
                  key: password
            - name: MQTT_BASE_TOPIC
              value: rtlamr
            - name: METER_ID
              value: 38260230,34406225
            - name: RTL_TCP_SERVER
              value: 192.168.0.10:2001
          resources:
            requests:
              memory: 32Mi
              cpu: 400m
            limits:
              memory: 64Mi
              cpu: 500m
