apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: deepstack
  name: deepstack-datastore
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homelab-longhorn
  resources:
    requests:
      storage: 10Gi
