apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kea
resources:
  - namespace.yaml
  - service.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - statefulset.yaml
images:
  - name: kea
    newName: docker.cloudsmith.io/isc/docker/kea-dhcp4
    newTag: 2.5.2
