apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: kea
  name: dhcp4-leases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homelab-longhorn
  resources:
    requests:
      storage: 100Mi
