apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: kea
  name: kea-leases
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.8
    path: "/volume1/kea-leases"