apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: kea-dhcp4
  name: kea-dhcp4
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.36
  ports:
    - name: "67"
      port: 67
      protocol: UDP
  externalTrafficPolicy: Local
  selector:
    app: kea-dhcp4
