apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: channels-dvr
  annotations:
  name: channels-dvr
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.34
  ports:
    - name: "8089"
      port: 8089
  selector:
    app: channels-dvr
