apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: channels-dvr
  name: channels-dvr
spec:
  replicas: 1
  serviceName: channels-dvr
  selector:
    matchLabels:
      app: channels-dvr
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: channels-dvr
    spec:
      containers:
        - image: fancybits/channels-dvr:tve
          name: channels-dvr
          ports:
            - containerPort: 8089
          volumeMounts:
            - mountPath: /channels-dvr
              name: channels-dvr
            - mountPath: /recordings
              name: recordings
          resources:
            requests:
              memory: 512Mi
              cpu: 0.5
            limits:
              gpu.intel.com/i915: 1
              memory: 1Gi
              cpu: 2
        - image: jonmaddox/pluto-for-channels
          name: pluto-for-channels
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: 16Mi
              cpu: 50m
            limits:
              memory: 16Mi
              cpu: 50m
      restartPolicy: Always
      volumes:
        - name: channels-dvr
          persistentVolumeClaim:
            claimName: channels-dvr
        - name: recordings
          persistentVolumeClaim:
            claimName: channels-dvr-recordings
