apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: airflow
resources:
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
  - deployment-scheduler.yaml
  - deployment-webserver.yaml
  - ingress.yaml
  - configmap.yaml
  - service.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
images:
  - name: airflow
    newName: apache/airflow
    newTag: 2.3.1