kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-scheduler
  labels:
    app: airflow
    component: scheduler
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-webserver
  labels:
    app: airflow
    component: webserver
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: airflow-worker
  labels:
    app: airflow
    component: worker
