apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
resources:
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
  - persistentvolume.yaml
images:
  - name: homeassistant
    newName: ghcr.io/home-assistant/home-assistant
    newTag: 2024.9.3
  - name: hass-configurator
    newName: causticlab/hass-configurator-docker
    newTag: 0.5.2
  - name: piper
    newName: lscr.io/linuxserver/piper
    newTag: latest