apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: homeassistant
  name: homeassistant-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homelab-longhorn
  resources:
    requests:
      storage: 5Gi
