apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: homeassistant
  name: homeassistant-media
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.8
    path: "/volume1/homeassistant-media"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: homeassistant
  name: homeassistant-config
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.8
    path: "/volume1/homeassistant-config"
