apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - port: 8123
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homekit
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.37
  selector:
    app: homeassistant
  ports:
    - port: 21063
