apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
    - port: 8123
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homekit
  annotations:
    metallb.universe.tf/allow-shared-ip: homekit
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.37
  selector:
    app: homeassistant
  ports:
    - port: 21063
      targetPort: 21063
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homekit-front-door-camera
spec:
  type: NodePort
  selector:
    app: homeassistant
  ports:
    - port: 21064
      nodePort: 21064
      targetPort: 21064
      protocol: TCP
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: hass-configurator
spec:
  selector:
    app: homeassistant
  ports:
    - port: 3218
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homekit-front-door-lock
  annotations:
    metallb.universe.tf/allow-shared-ip: homekit
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.37
  selector:
    app: homeassistant
  ports:
    - port: 21065
      targetPort: 21065
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homekit-driveway-camera
spec:
  type: NodePort
  selector:
    app: homeassistant
  ports:
    - port: 21066
      nodePort: 21066
      targetPort: 21066
      protocol: TCP
  externalTrafficPolicy: Local
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: piper
spec:
  selector:
    app: homeassistant
  ports:
    - port: 10200