apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  replicas: 1
  serviceName: homeassistant
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: homeassistant
          imagePullPolicy: IfNotPresent
          ports:
            - name: homeassistant
              containerPort: 8123
            - name: homekit
              containerPort: 21063
          volumeMounts:
            - mountPath: /config
              name: homeassistant-config
            - mountPath: /media
              name: homeassistant-media
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            httpGet:
              path: /
              port: homeassistant
          resources:
            requests:
              memory: 512Mi
              cpu: 500m
            limits:
              memory: 1024Mi
              cpu: 1000m
              smarter-devices/zigbee: 1
        - name: hass-configurator
          image: hass-configurator
          imagePullPolicy: IfNotPresent
          ports:
            - name: configurator
              containerPort: 3218
          volumeMounts:
            - mountPath: /hass-config
              name: homeassistant-config
          envFrom:
            - configMapRef:
                name: hass-configurator
          env:
            - name: HC_USERNAME
              valueFrom:
                secretKeyRef:
                  name: hass-configurator
                  key: username
            - name: HC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hass-configurator
                  key: password
            - name: HC_HASS_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hass-configurator
                  key: hass-api-password
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 15
            tcpSocket:
              port: configurator
          resources:
            requests:
              memory: 16Mi
              cpu: 10m
            limits:
              memory: 32Mi
              cpu: 100m

      volumes:
        - name: homeassistant-config
          persistentVolumeClaim:
            claimName: homeassistant-config
        - name: homeassistant-media
          persistentVolumeClaim:
            claimName: homeassistant-media
