apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: gdrapp@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
      - dns01:
          route53:
            region: us-east-1
            hostedZoneID: Z1HBQIP1JOJBDO
            accessKeyID: AKIAZCR7GBUFLG6KCQFK
            secretAccessKeySecretRef:
              name: route53-credentials
              key: secret-access-key
        selector:
          dnsZones:
            - "gregrapp.net"
