apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app: rtl-433
data:
  rtl_433.conf: |
    device rtl_tcp://192.168.0.10:2000
    protocol 74  # Acurite 00275rm,00276rm Temp/Humidity with optional probe
    protocol 163 # Acurite 590TX Temperature with optional Humidity
    protocol 11  # Acurite 609TXC Temperature and Humidity Sensor
