apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: mysql
  name: data
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.8
    path: "/volume1/mysql-data"