apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  replicas: 1
  serviceName: mysql
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.29
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root
                  key: password
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
            - name: confd
              mountPath: /etc/mysql/conf.d
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m
          livenessProbe:
            exec:
              command:
                - "bash"
                - "-c"
                - |
                  mysqladmin -u root --password=$MYSQL_ROOT_PASSWORD --connect-timeout=5 ping
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - "bash"
                - "-c"
                - |
                  mysql -u root --password=$MYSQL_ROOT_PASSWORD --connect-timeout=5 -e 'SELECT 1'
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: confd
          configMap:
            name: confd