apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zwavejs2mqtt
resources:
  - namespace.yaml
  - persistentvolumeclaim.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
