apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: zwavejs2mqtt
resources:
  - namespace.yaml
  - persistentvolume.yaml
  - persistentvolumeclaim.yaml
  - statefulset.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: zwavejs2mqtt
    newName: zwavejs/zwave-js-ui
    newTag: 9.14.6