apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: zwavejs2mqtt
  name: zwavejs-config
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.0.8
    path: "/volume1/zwavejs-config"