apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mosquitto
  name: mosquitto
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.38
  ports:
    - port: 1883
  selector:
    app: mosquitto
