apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
resources:
  - namespace.yaml
  - deployment.yaml
images:
  - name: cloudflared
    newName: cloudflare/cloudflared
    newTag: 2023.6.1-amd64