apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  labels:
    app: unbound
spec:
  replicas: 3
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - unbound
              topologyKey: kubernetes.io/hostname
      containers:
        - name: unbound
          image: ghcr.io/gdrapp/unbound-container:master
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 53
              protocol: UDP
          volumeMounts:
            - mountPath: /etc/unbound/unbound.conf
              subPath: unbound.conf
              name: config
          resources:
            requests:
              memory: 32Mi
              cpu: 10m
            limits:
              memory: 32Mi
              cpu: 20m
      priorityClassName: highest
      volumes:
        - name: config
          configMap:
            name: unbound
