apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: unbound
  name: unbound
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.35
  ports:
    - name: "53"
      port: 53
      protocol: UDP
  externalTrafficPolicy: Local
  selector:
    app: unbound
